version: "3"

services:
  postgres:
    image: postgres:11.9
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    ports:
      - "3306:5432"
    restart: always